### PR TITLE
Final 50% pull

### PR DESCRIPTION
**Pull request by Zalobomb**

### CODE REVIEW

**Review by jnirwin91 — APPROVED** [review]
Some tests failing sporadically!

**Review by shmee360 — DISMISSED** [review]
Looks good to me

**Comment by jordon-ogo** [comment]
Looks great! Sometimes (inconsistently) the "wrongUsernameTest()" in LoginActivityTest fails. Sometimes without making any changes to the code it passes. Manual testing shows no problems. It might have to do with having a a db call within a db call within a db call.

**Review by jordon-ogo — APPROVED** [review]
Looks great! Sometimes (inconsistently) the "wrongUsernameTest()" in LoginActivityTest fails. Sometimes without making any changes to the code it passes. Manual testing shows no problems. It might have to do with having a a db call within a db call within a db call.

**Pull request merged**
